### ISSUE TITLE
TypeError: DebianGBPRelease._create_from_repo() missing 1 required positional argument: 'debversion'

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/moncic-ci#106]
```
$ monci ---version
0.14

$ monci ci --debug --source-type debian-gbp-release --branch ubuntu/jammy/3.38-1 ubuntujammy https://github.com/ARPA-SIMC/wreport
2024-09-04 12:43:27 DEBUG moncic.system ubuntujammy: look for configuration on /var/lib/machines/ubuntujammy.yaml
2024-09-04 12:43:27 DEBUG moncic.system ubuntujammy: look for configuration on /home/edigiacomo@ARPA.EMR.NET/.config/moncic-ci/ubuntujammy.yaml
2024-09-04 12:43:27 DEBUG moncic.system ubuntujammy: configuration found at /home/edigiacomo@ARPA.EMR.NET/.config/moncic-ci/ubuntujammy.yaml
2024-09-04 12:43:27 DEBUG moncic.system ubuntujammy: image pathname: /var/lib/machines/ubuntujammy
2024-09-04 12:43:27 INFO run /tmp/tmprg8cuwpl$ git -c advice.detachedHead=false clone --quiet https://github.com/ARPA-SIMC/wreport --branch ubuntu/jammy/3.38-1
2024-09-04 12:43:29 DEBUG git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=/tmp/tmprg8cuwpl/wreport, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-09-04 12:43:29 DEBUG git.cmd Popen(['git', 'checkout', 'moncic-ci'], cwd=/tmp/tmprg8cuwpl/wreport, stdin=None, shell=False, universal_newlines=False)
Traceback (most recent call last):
  File "/usr/bin/monci", line 48, in <module>
    cli.run_main(main)
  File "/usr/lib/python3.11/site-packages/moncic/cli/base.py", line 68, in run_main
    sys.exit(func())
             ^^^^^^
  File "/usr/bin/monci", line 44, in main
    return handler.run()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/moncic/cli/build.py", line 79, in run
    with self.source(system.distro, self.args.source) as source:
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/moncic/cli/moncic.py", line 279, in source
    source = source_cls.create(distro, input_source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/moncic/source/debian.py", line 183, in create
    return cls._create_from_repo(distro, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DebianGBPRelease._create_from_repo() missing 1 required positional argument: 'debversion'
```

**Comment by spanezz** [comment]
In teoria, la fix è facile. In pratica il bug solleva la questione che moncic-ci andrebbe ripulito un po' per avere questo problema testato nei test, e/oo da mypy.

Ci sto lavorando, che un po' di pulizia inizia a essere necessaria e mi sono anche venute un po' di idee
