### ISSUE TITLE
bootstrap on a non-btrfs filesystem fails

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/moncic-ci#44]
moncic-ci-0.4-2 on a Fedora 34, tested with a ext4 and a tmpfs filesystem:

```
# monci bootstrap --verbose --imagedir ~/buttami fedora36
2022-05-10 11:49:29 INFO moncic.ci fedora36: bootstrapping subvolume
2022-05-10 11:49:29 INFO system.fedora36 Running btrfs -q subvolume create /root/buttami/fedora36
2022-05-10 11:49:29 INFO system.fedora36 stderr: ERROR: not a btrfs filesystem: /root/buttami
2022-05-10 11:49:29 CRITICAL moncic.ci fedora36: cannot create image
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/moncic/ci.py", line 292, in run
    system.bootstrap()
  File "/usr/lib/python3.9/site-packages/moncic/system.py", line 283, in bootstrap
    with subvolume.create():
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/site-packages/moncic/btrfs.py", line 39, in create
    self.system.local_run(["btrfs", "-q", "subvolume", "create", self.path])
  File "/usr/lib/python3.9/site-packages/moncic/system.py", line 201, in local_run
    return runner.execute()
  File "/usr/lib/python3.9/site-packages/moncic/runner.py", line 193, in execute
    return asyncio.run(self._run())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/moncic/runner.py", line 215, in _run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['btrfs', '-q', 'subvolume', 'create', '/root/buttami/fedora36']' returned non-zero exit status 1.
```

**Comment by spanezz** [comment]
Running a build probably works, but bootstrapping at the moment does not. Whoops!

I'm working on it

**Comment by spanezz** [comment]
I pushed a draft implementation of bootstrapping on non-btrfs filesystems. Could you try it out?

**Comment by brancomat** [comment]
Fixed in v0.5
