### ISSUE TITLE
monci run --clone fails

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/moncic-ci#89]
I'm trying to run a container using a local repository

```
$ ./monci run --clone . --debug rocky8 /bin/bash
2023-03-28 15:04:44 DEBUG moncic.system rocky8: look for configuration on /var/lib/machines/rocky8.yaml
2023-03-28 15:04:44 DEBUG moncic.system rocky8: look for configuration on /home/edg/.config/moncic-ci/rocky8.yaml
2023-03-28 15:04:44 DEBUG moncic.system rocky8: configuration found at /home/edg/.config/moncic-ci/rocky8.yaml
2023-03-28 15:04:44 DEBUG moncic.system rocky8: image pathname: /var/lib/machines/rocky8
2023-03-28 15:04:44 DEBUG asyncio Using selector: EpollSelector
2023-03-28 15:04:44 INFO system.rocky8 Running git -c advice.detachedHead=false clone /home/edg/devel/arpae/moncic-ci
2023-03-28 15:04:44 INFO system.rocky8 stderr: Cloning into 'moncic-ci'...
2023-03-28 15:04:44 INFO system.rocky8 stderr: done.
Traceback (most recent call last):
  File "/home/edg/devel/arpae/moncic-ci/./monci", line 42, in <module>
    cli.run_main(main)
  File "/home/edg/devel/arpae/moncic-ci/moncic/cli/base.py", line 68, in run_main
    sys.exit(func())
  File "/home/edg/devel/arpae/moncic-ci/./monci", line 38, in main
    return handler.run()
  File "/home/edg/devel/arpae/moncic-ci/moncic/cli/run.py", line 44, in run
    with self.container() as container:
  File "/usr/lib64/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/edg/devel/arpae/moncic-ci/moncic/cli/moncic.py", line 201, in container
    config.configure_workdir(workdir, bind_type=workdir_bind_type)
UnboundLocalError: local variable 'workdir_bind_type' referenced before assignment
```

**Comment by edigiacomo** [comment]
If I understand correctly, it might be enough to set `workdir_bind_type = "volatile"` when the option `--clone` is set.
