### ISSUE TITLE
monci ci fails when branch is a tag

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/moncic-ci#99]
```
 $ monci ci --debug  --branch ubuntu/jammy/3.35-1 ubuntujammy https://github.com/ARPA-SIMC/wreport
2023-05-26 11:22:34 DEBUG moncic.system ubuntujammy: look for configuration on /var/lib/machines/ubuntujammy.yaml
2023-05-26 11:22:34 DEBUG moncic.system ubuntujammy: look for configuration on /home/edg/.config/moncic-ci/ubuntujammy.yaml
2023-05-26 11:22:34 DEBUG moncic.system ubuntujammy: configuration found at /home/edg/.config/moncic-ci/ubuntujammy.yaml
2023-05-26 11:22:34 DEBUG moncic.system ubuntujammy: image pathname: /var/lib/machines/ubuntujammy
2023-05-26 11:22:35 INFO run /tmp/tmpd8arc009$ git -c advice.detachedHead=false clone --quiet https://github.com/ARPA-SIMC/wreport --branch ubuntu/jammy/3.35-1
2023-05-26 11:22:36 DEBUG git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=/tmp/tmpd8arc009/wreport, universal_newlines=False, shell=None, istream=<valid stream>)
Traceback (most recent call last):
  File "/usr/bin/monci", line 42, in <module>
    cli.run_main(main)
  File "/usr/lib/python3.10/site-packages/moncic/cli/base.py", line 68, in run_main
    sys.exit(func())
  File "/usr/bin/monci", line 38, in main
    return handler.run()
  File "/usr/lib/python3.10/site-packages/moncic/cli/build.py", line 71, in run
    with self.source(system.distro, self.args.source) as source:
  File "/usr/lib64/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/site-packages/moncic/cli/moncic.py", line 244, in source
    input_source = input_source.branch(self.args.branch)
  File "/usr/lib/python3.10/site-packages/moncic/source/inputsource.py", line 232, in branch
    return self.clone(branch).branch(branch)
  File "/usr/lib/python3.10/site-packages/moncic/source/inputsource.py", line 199, in branch
    if self.repo.active_branch == branch:
  File "/usr/lib/python3.10/site-packages/git/repo/base.py", line 881, in active_branch
    return self.head.reference
  File "/usr/lib/python3.10/site-packages/git/refs/symbolic.py", line 309, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '0cd156d1e6d3b74a4a321d4554b6d072291c3e75'
```

**Comment by edigiacomo** [comment]
```
$ cat ~/.config/moncic-ci/ubuntujammy.yaml 
distro: jammy
maintscript: |
    set -uxe
    sed -i -re 's/main$/main universe/' /etc/apt/sources.list
    apt-get update
    apt-get -y install build-essential dpkg-dev fakeroot git eatmydata iproute2 git-buildpackage
```
